// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-uqdt0Hp8TEQxsvu6BPC-40Xlf1YipCo',
    appId: '1:58143625498:web:f3a028433195417e66dca3',
    messagingSenderId: '58143625498',
    projectId: 'coffeeapp-2b68e',
    authDomain: 'coffeeapp-2b68e.firebaseapp.com',
    storageBucket: 'coffeeapp-2b68e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGcHWMgHog-415OAn_gvgIieDI_dvaDQc',
    appId: '1:58143625498:android:d89401c2dfa8ac3b66dca3',
    messagingSenderId: '58143625498',
    projectId: 'coffeeapp-2b68e',
    storageBucket: 'coffeeapp-2b68e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_jrwt1rNddh50VglMfVJYGcYai9xefkI',
    appId: '1:58143625498:ios:4b41ad751370097966dca3',
    messagingSenderId: '58143625498',
    projectId: 'coffeeapp-2b68e',
    storageBucket: 'coffeeapp-2b68e.appspot.com',
    iosBundleId: 'com.example.coffeeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_jrwt1rNddh50VglMfVJYGcYai9xefkI',
    appId: '1:58143625498:ios:7e37b503b600d9ce66dca3',
    messagingSenderId: '58143625498',
    projectId: 'coffeeapp-2b68e',
    storageBucket: 'coffeeapp-2b68e.appspot.com',
    iosBundleId: 'com.example.coffeeapp.RunnerTests',
  );
}
